# SITE CONFIGURATION
#:baseurl: "/akunewb.github.io"
url: "https://www.tipsrandom.eu.org"
permalink: /:title/
locale: "id-ID"
# THEME-SPECIFIC CONFIGURATION
title: Tips Random                               # site's title
description: "Website yang membahas tentang banyak hal"      # used by search engines
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab
breadcrumbs: true
word_per_minute: 200

# Header and footer text
header_text: Tips Random Website Belajar Perkantoran Belajar Perhotelan 
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Powered by <a href="/">RandomTips</a> with <a href="/">Love</a> 
  <p> <a> <a href="/about/">  About</a> | <a href="/disclaimer/">Disclaimer</a> | <a href="/privacy/">Privacy Policy</a> | <a href="/contact/">Contact</a> | <a href="/sitemap/">Sitemap</a> </a>


# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
# disqus_shortname: adminperkantoran                                # Your discus shortname for comments
#cusdis_app_id:                                          # Your cusdis data-app-id
color_theme: auto                                       # auto, dark or light

# PAGINATION
paginate: 5
paginate_path: "/page:num"

search: true
search_full_content: true
search_provider: lunr

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-include-cache, jekyll-sitemap]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
# remote_theme: /Type-on-Strap                     # If using as a remote_theme in github
