# SITE CONFIGURATION
#:baseurl: "/akunewb.github.io"
url: "https://tipsrandom.eu.org"
permalink: /:title/
locale: "id-ID"
# THEME-SPECIFIC CONFIGURATION
title: Tips Random                               # site's title
tagline: " — Informasi Tips Random 🌱"
name: "Tips Random"
author_bio:
  "Seorang Penulis sekaligus pembaca informasi yang ada di internet."
description: "Website yang membahas tentang banyak hal"      # used by search engines
footer_description:
  'Blog tentang Informasi Tips Random Seputar Teknologi, Perkantoran, Otomasi, Cara Ternak'
notes_url: "https://akunewb.github.io/enjoyment/notes"
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab
breadcrumbs: true
word_per_minute: 200

# Header and footer text
header_text: Tips Random Website
Belajar Perkantoran, Belajar Perhotelan, Cara Ternak 
footer_text: >
  Powered by <a href="/">RandomTips</a> with <a href="/">Love</a> 
  <p> <a> <a href="/about/">  About</a> | <a href="/disclaimer/">Disclaimer</a> | <a href="/privacy/">Privacy Policy</a> | <a href="/contact/">Contact</a> | <a href="/sitemap/">Sitemap</a> </a>


# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
# disqus_shortname: adminperkantoran                                # Your discus shortname for comments
#cusdis_app_id:                                          # Your cusdis data-app-id
color_theme: auto                                       # auto, dark or light

# PAGINATION
paginate: 5
paginate_path: "/page:num"

search: true
search_full_content: true
search_provider: lunr

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-include-cache, jekyll-sitemap]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdnmkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerp_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_warp: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
sass:
 sass_dir: _sass
 style: compressed
  
# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
# remote_theme: /Type-on-Strap                     # If using as a remote_theme in github

author:
  name : tipsrandom.eu.org
  bio: Blogging enthusiast, tips random, menyukai Amira Shabirina Noor
  location: Indonesia
  email: tipsrandomeuorg@gmail.com

defaults: 

   value:
     layout : single
     read_time: true
     toc: true
     toc_label: "Menu"
     comments: true
     share: true
     related: true
     autoads: true
     
   
   
   
